### ISSUE TITLE
运行命令出错——Coredumped&Segmentation fault

### ISSUE THREAD

**Issue by chengxuanlu** [NathanUA/ground-truth-labeling#5]
分别在ubuntu18.04和ubuntu16.04上下载代码，运行命令，得到Bus Error(core dumped)和segmentationfault错误，根据查博客的结果，前者是指针对齐的问题，后者是内存访问的问题，但是我都无从下手，麻烦可以帮忙看看吗

**Comment by chengxuanlu** [comment]
已经编译过，不需要安装opencv对吧。针对 core dumped问题，我开始以为是内存不足，清理了不用的内核，但是错误还是存在

**Comment by xuebinqin** [comment]
这个静态库编译是在Ubuntu 14.04和一个比较老的机器上编译的，所以有些问题。如果要自己编译的话，首先将Makefile的line 17改成：$(lnk) $(dbg) -o bylabel $(objRRC) pkg-config --libs opencv EDLib.a EDLinesLib.a （因为我们之前的Makefile用的是静态编译，我们把所有依赖库都加进去了，但是其实如果你重新动态编译，这些库都是不需要的），然后make一下试试，但是在make编译之前需要安装opencv 2.4.9或者之后的版本，而且在安装的时候需要，保持QT=enable,否则无法通过鼠标滚轮缩放图片。

**Comment by chengxuanlu** [comment]
好的，那我先试一下，谢谢你！

**Comment by chengxuanlu** [comment]
重新编译后运行没问题了！哈哈，不过Makefile里line17需要更新的代码是 $(lnk) $(dbg) -o bylabel $(objRRC) `pkg-config --libs opencv` EDLib.a EDLinesLib.a，需要加引号呢

**Comment by xuebinqin** [comment]
好的，多谢提醒。
